---
- name: A generic management playbook for elasticsearch
  hosts: "{{ __target__ | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - packages
    - hosts
    - secrets
    - configuration
    - elasticsearch
    - kibana
